### ISSUE TITLE
PR Workflow

### ISSUE THREAD

**Issue by alexander-myltsev** [GlobalNamesArchitecture/GlobalNamesArchitecture.github.io#11]
So, we you did merge PRs to `master`. How those commits appear to `jekyll` branch? Should it be done by the person who merged to `master`, or some other person who starts working in `jekyll`?

**Comment by dimus** [comment]
I would not bother with pull requests for blog. Lets follow what is in README and if we find that PRs are necessary, we will change the workflow. I think in general when we work on documentation/papers PRs are overkill, with gnparser paper we had no PRs and I don't think it was a problem.
