### ISSUE TITLE
Limahlania crenulata incorrectly mapping to Macleania crenulata

### ISSUE THREAD

**Issue by crowleyb** [GlobalNamesArchitecture/GlobalNamesArchitecture.github.io#19]
The Gardener's Bulletin, Singapore references for Macleania crenulata are all incorrect. They are citing a totally different genus! Please delete these three pages from citing Macleania crenulata!

https://www.biodiversitylibrary.org/name/Macleania_crenulata

**Comment by mlichtenberg** [comment]
I have cleaned up the incorrect mapping of Limahlania crenulata to Macleania crenulata.

**Comment by dimus** [comment]
Thanks @mlichtenberg!
