### ISSUE TITLE
avian taxonomies

### ISSUE THREAD

**Issue by ccicero** [GlobalNamesArchitecture/GlobalNamesArchitecture.github.io#25]
Arctos pulls taxonomy classifications from Global Names. I was asking @dustymc about adding avian taxonomies from spreadsheets into Arctos, and he suggested the better approach was to add them to Global Names (contact @dimus) which would benefit Arctos and the broader community. Is this feasible. These are updated ~annually, but here are the lists I was thinking of:

IOC World Bird List - https://www.worldbirdnames.org/ioc-lists/master-list-2/
Clements Checklist - https://www.birds.cornell.edu/clementschecklist/download/
AOS Checklist - http://checklist.americanornithology.org/taxa/
Howard and Moore Checklist - https://www.howardandmoore.org/howard-and-moore-database/

Thanks!

**Comment by dimus** [comment]
I'll put it to my TODO list, I think I can import them by the end of May. @dustymc, can I ask you also to send me recent Arctos  data? It is about a year since we updated Arctos, would be good to refresh it.

**Comment by dustymc** [comment]
Hey @dimus we're moving to some new infrastructure, should be there within the month, I can get you CSV then - or we should then be able to support an API or something of the sort if you want....

**Comment by dimus** [comment]
@dustymc fantastic, yes having a stable endpoint with the data dump would be great.

**Comment by ccicero** [comment]
Excellent, thanks @dimus and @dustymc !

**Comment by ccicero** [comment]
In thinking about this, the lists should be updated again this summer, probably July-August. So maybe best to wait until after that - say September 1?

**Comment by dimus** [comment]
If there is a stable endpoint for Arctos dump, it would not really matter. I tend to update major databases about twice a year, so if I harvest data in June or so, it means in December I will have all the scripts ready, and update wil be easy. So I think it is better if we harvest what is available soon, and share feedback, and establish the process. It will make future harvests easier.

**Comment by ccicero** [comment]
Great Dmitry, thanks!

**Comment by ccicero** [comment]
Hi Dmitry - Following up on this to see if you can incorporate those avian lists into GlobalNames.  Thanks, Carla

**Comment by dimus** [comment]
hi @ccicero, I did add them in May of 2020, is there a problem for you in accessing them?
