### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by allie-tatarian** [GlobalNamesArchitecture/GlobalNamesArchitecture.github.io#35]
On the [Introduction](https://globalnames.org/docs/home/) page, the link to Rich Pyle's blog post (http://www.tdwg.org/fileadmin/2008conference/slides/Pyle_03_01_Taxonomic_Names_of_Organisms.swf) appears to be broken.

**Comment by dimus** [comment]
@allie-tatarian, thank you for letting us know

@deepreef do you still have these slides? I love them, would be great to show them again at globalnames.org

**Comment by dimus** [comment]
After much help from @deepreef, @stanblum, @WUlate, and @debpaul we have the talk on YouTube now

https://www.youtube.com/watch?v=vPVm5S0qIcs

I am updating the link

@deepreef said he wants to create an updated version too!
